### ISSUE TITLE
JMMobileDevicePort crashes when unplugging USB while writing data

### ISSUE THREAD

**Issue by kirankunigiri** [jensmeder/DarkLightning#34] opened 2016-12-26 02:48 UTC
I'm using `writeData()` on a JMMobileDevicePort instance once every 0.01 seconds. However, when I disconnect the USB device, the connection is being disrupted at the same time it writes the data, and the app crashes. Is a workaround or a fix possible for this?

**Comment by jensmeder** [comment] 2016-12-26 09:45
I assume the underlying `NSOutputStream` crashes (`NSOutputStream` is prone to crashes). Might be possible to do a quick fix in the `writeData` method on `JMSocketConnection`. I'll have a look at it.

**Comment by jensmeder** [comment] 2017-01-10 20:07
I have found the cause of the bug and just pushed a fix. Will publish a new release of DarkLightning in the next hour. Sorry for the delay! 

You can check it out on this [branch](https://github.com/jensmeder/DarkLightning/tree/%2334-JMMobileDevicePort-crashes-when-unplugging-USB-while-writing-data). 

Thanks for reporting the bug!

**Comment by jensmeder** [comment] 2017-01-10 20:26
Fixed in 1.0.2

**Closed by jensmeder** 2017-01-10 20:26 UTC
Labels: bug
